### ISSUE TITLE
Virtual datasets via task graph serializaiton

### ISSUE THREAD

**Issue by nsmith-** [jpivarski/PyHEP.dev#28]
If a task graph which transforms input data is available (as would be with `uproot.lazy` + dask-awkward), the following are interchangeable representations of a reduced output dataset for the purpose of caching:

- Serialized task graph + input data
- Serialized partial task graph + partially-reduced input data
- Output dataset

What do we need to make a caching system that can optimize between these?

**Comment by lgray** [comment]
Yes - we do.

**Comment by lgray** [comment]
Dask distributed's dataset interface is an interesting thread to pull on here (when mixed with dask.persist and company).

**Comment by btovar** [comment]
+1
