### ISSUE TITLE
200 Gbps Challenge discussion and future plans

### ISSUE THREAD

**Issue by oshadura** [jpivarski/PyHEP.dev#30]

**Comment by eduardo-rodrigues** [comment]
Interested 👍.

**Comment by ynikitenko** [comment]
How is that connected with Python?

**Comment by matthewfeickert** [comment]
> How is that connected with Python?

@ynikitenko The whole 200 Gbps challenge relies on the Scientific Python and Scikit-HEP, PyHEP, and IRIS-HEP stack of Pythonic tools. So this is pushing our Pythonic tooling to find weak points and rough edges.

c.f. https://github.com/iris-hep/idap-200gbps and https://indico.cern.ch/event/1369601/contributions/5924000/

**Comment by eduardo-rodrigues** [comment]
This was a grand topic at the workshop, with talks dedicated to it. Closing at this point.
