### ISSUE TITLE
Statistical tools: bridging experiments

### ISSUE THREAD

**Issue by pfackeldey** [jpivarski/PyHEP.dev#33]

**Comment by kratsg** [comment]
We should also bring up HS3 compatibility/integration with tools like pyhf (/cc @lukasheinrich @matthewfeickert @cburgard @jonas-eschle @alexander-held )

Ref: https://github.com/scikit-hep/pyhf/pull/2397

**Comment by eduardo-rodrigues** [comment]
This was a grand topic at the workshop, with talks dedicated to it. Closing at this point.
