### ISSUE TITLE
Mixing Julia and Python: Language interoperability and environments

### ISSUE THREAD

**Issue by pfackeldey** [jpivarski/PyHEP.dev#36]

**Comment by matthewfeickert** [comment]
@pfackeldey, while I know @ianna and @Moelf have experience here, can you comment a bit more on some of the ideas that you'd want to investigate or example problems that you'd like to try to solve?

**Comment by pfackeldey** [comment]
I'd be especially interested in how to package a python project that uses Julia (and also other non-C++ languages like Rust)  and how to manage isolated & self-contained environments for developing such projects.

**Comment by Moelf** [comment]
The most production-grade examples of python package using Julia as backend are probably:
- https://github.com/SciML/diffeqpy
- https://github.com/MilesCranmer/PySR

For environment isolation, if the main environment is python, then it's simple to just let Julia dependency to always check out a Manifest.toml

**Comment by eduardo-rodrigues** [comment]
There was a specific talk at the workshop on this topic. Closing at this point.
