### ISSUE TITLE
Overview of HEP software

### ISSUE THREAD

**Issue by ynikitenko** [jpivarski/PyHEP.dev#41]
In https://github.com/HSF/PyHEP.dev-workshops/issues/31 there was mentioned a "typical HEP analysis". It would be interesting to get an overview of contemporary HEP software tools and practices, including:

- tools for scientific workflow. From low level to tools for prepared publications,
- balance between custom (local) and general (open source, free) tools in an experiment,
- Python vs other languages in an experiment,
- collaboration software for its managers vs users (e.g. a student vs a person responsible for collaboration analysis),
- balance between HEP and general software (purely scientific vs common testing, documentation frameworks, etc.)
- main problems/challenges/desires for the existing scientific software.

**Comment by eduardo-rodrigues** [comment]
Some of this got discussed, sometimes at length. Closing at this point as the topic could go well beyond that of the workshop.

Note that we do try and maintain a repository with resources - https://github.com/hsf-training/PyHEP-resources.
